[project]
name = "LLM-gateway"
version = "1.2.0"
description = "Cổng API và giao diện chat cho nhiều mô hình ngôn ngữ"
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
authors = [
    {name = "Minh Nhat"}
]

dependencies = [
    "cohere",
    "fastapi",
    "google-genai>=2.12.1",
    "langchain>=1.0,<2",
    "langgraph>=1.0,<2",
    "openai",
    "python-dotenv",
    "qdrant-client",
    "streamlit>=1.40",
    "uvicorn",
    "supabase",
    "pydantic-settings"]
    
    
[project.optional-dependencies]
dev = [
    "httpx",
    "pytest",
]

[tool.setuptools.packages.find]
include = ["models*", "Tools*"]
